### ISSUE TITLE
[IgnisCharacterAfterImage] Loading of old save files breaks after changing plugin settings

### ISSUE THREAD

**Issue by masked-rpgmaker** [comuns-rpgmaker/Ignis-Engine#2]
**Reporter:** Jami Cassidy (via Discord)

**Description:** When you first load the plugin into the project and after you change the plugin configuration, trying to load an old save file will throw an exception.

**Error message:**
```
TypeError: Cannot read property `length` of undefined
```

**Steps to reproduce:** Without having the plugin installed, create a save file. Then install the plugin and try to load said file.
Alternatively, have the plugin installed, create a save file, change the plugin configuration and then try to load it.

**Correction suggestion:** Proactive detection and graceful recovery.

**Comment by Raizen884** [comment]
Issue fixed
